---
- name: DEBUG stats_consul_list
  debug:
    var: stats_consul_list

- name: INSTALL package
  package:
    name:
      - git
    state: present

- name: CREATE NAP directoty
  file:
    path: "/etc/nginx/nap"
    state: directory

- name: FETCH git NAP configuration
  git:
    repo: '{{ extra_nap_repo }}'
    dest: "/etc/nginx/nap/"

- name: Enable NAP module
  lineinfile:
    path: /etc/nginx/nginx.conf
    firstmatch: yes
    insertbefore: "events {"
    line: "{{ lookup('template','nap_module.json') }}"

- name: app protect directives
  set_fact:
    var_replace_app_protect:
      - app_protect_enable
      - app_protect_security_log
      - app_protect_logging_str
      - app_protect_security_log_enable

- name: CLEAN - comment app protect configuration set by NGINX Controller
  replace:
    path: /etc/nginx/nginx.conf
    regexp: '^(\s+{{ item }}.*)$'
    replace: '#\1'
  loop: "{{ var_replace_app_protect }}"

- name: Enable WAF default policy
  blockinfile:
    path: /etc/nginx/nginx.conf
    insertafter: "http {"
    block: "{{ lookup('template','nap_default_policy.json') }}"
    marker: "# {mark} Ansible - Enable default policy"

- name: Enable WAF specific policy
  blockinfile:
    path: /etc/nginx/nginx.conf
    insertafter: "server_name {{ item.key }};"
    block: "{{ lookup('template','nap_specific_policy.json') }}"
    marker: "# {mark} Ansible - Enable specific policy for {{ item.key }}"
  loop: "{{ stats_consul_list }}"

- name: reload nginx
  service:
    name: nginx
    state: reloaded

...